@extends('admin.layouts.app')
@section('header', 'Franquicias')
@section('content')
<style>
.franchise-page{max-width:1100px;margin:0 auto}.franchise-hero{padding:24px;border-radius:18px;background:linear-gradient(120deg,#7d2100,#e85d04,#ff8a19);color:white;margin-bottom:20px}.franchise-hero h2{margin:0 0 6px;font-size:1.45rem;font-weight:900}.franchise-hero p{margin:0;opacity:.9}.franchise-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}.franchise-card{padding:18px;border:1px solid #e7e9ee;border-radius:16px;background:#fff;box-shadow:0 5px 16px rgba(15,23,42,.05)}.franchise-card h3{margin:0;font-size:1.05rem;font-weight:850}.franchise-card p{margin:8px 0;color:#64748b;font-size:.84rem;min-height:38px}.franchise-form{display:grid;gap:10px}.franchise-form label{display:grid;gap:4px;font-size:.78rem;font-weight:800;color:#475569}.franchise-form input,.franchise-form textarea{width:100%;border:1px solid #cbd5e1;border-radius:9px;padding:9px 10px;font:inherit}.franchise-check{display:flex!important;align-items:center;gap:7px}.franchise-check input{width:auto!important}.franchise-save{border:0;border-radius:9px;padding:10px 12px;background:#e85d04;color:white;font:inherit;font-weight:800;cursor:pointer}.franchise-pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#fff0df;color:#9a3412;font-size:.7rem;font-weight:800}.franchise-add{border:1px dashed #fdba74;background:#fffaf5}
</style>
<div class="franchise-page"><section class="franchise-hero"><h2>Franquicias</h2><p>Separa el catálogo de cada marca o franquicia. Cada categoría y producto queda asociado a una franquicia para mantener la operación ordenada.</p></section>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<div class="franchise-grid">@foreach($franchises as $franchise)<article class="franchise-card"><div style="display:flex;justify-content:space-between;gap:8px"><div><h3>{{ $franchise->name }}</h3><span class="franchise-pill">{{ $franchise->slug }}</span></div>@if($franchise->is_default)<span class="franchise-pill" style="background:#dcfce7;color:#166534">Predeterminada</span>@endif</div><p>{{ $franchise->description ?: 'Sin descripción' }}<br><b>{{ $franchise->categories_count }}</b> categorías · <b>{{ $franchise->products_count }}</b> productos</p><form class="franchise-form" method="POST" action="{{ route('admin.franchises.update',$franchise) }}">@csrf @method('PUT')<label>Nombre<input name="name" value="{{ $franchise->name }}" required></label><label>Identificador<input name="slug" value="{{ $franchise->slug }}" required></label><label>Descripción<textarea name="description" rows="2">{{ $franchise->description }}</textarea></label><label class="franchise-check"><input type="checkbox" name="is_default" value="1" @checked($franchise->is_default)> Predeterminada</label><label class="franchise-check"><input type="checkbox" name="is_active" value="1" @checked($franchise->is_active)> Activa</label><button class="franchise-save">Guardar</button></form>@unless($franchise->is_default)<form method="POST" action="{{ route('admin.franchises.destroy',$franchise) }}" onsubmit="return confirm('¿Eliminar la franquicia {{ $franchise->name }}?');" style="margin-top:8px">@csrf @method('DELETE')<button class="franchise-save" style="background:#b91c1c" @if($franchise->categories_count || $franchise->products_count) disabled title="Tiene {{ $franchise->categories_count }} categoría(s) y {{ $franchise->products_count }} producto(s) asociados" @endif>Eliminar</button></form>@endunless</article>@endforeach
<article class="franchise-card franchise-add"><h3>Nueva franquicia</h3><p>Agrega otra marca administrada por la empresa.</p><form class="franchise-form" method="POST" action="{{ route('admin.franchises.store') }}">@csrf<label>Nombre<input name="name" placeholder="Ej.: DPIKEOS Express" required></label><label>Identificador<input name="slug" placeholder="dpikeos-express"></label><label>Descripción<textarea name="description" rows="2" placeholder="Descripción breve"></textarea></label><label class="franchise-check"><input type="checkbox" name="is_default" value="1"> Predeterminada</label><label class="franchise-check"><input type="checkbox" name="is_active" value="1" checked> Activa</label><button class="franchise-save">Crear franquicia</button></form></article></div></div>
@endsection
